# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f8d23eb426dcd2c323d89ea2efd02b4fd5773794da3bc5bb7afb5263005b5b25c6036606328b510910704e711f37dffe681b1fa6b6a1e70db0009b006b5f410

test:
  secret_key_base: f81beb061ae02f2a932011cee94777d78158b869ef06f99ea5d58bac3ecb96b15be77d4d41e658dc4adeffc3f4191a2bf0265888732c097a3f1a28da9f1ab160

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
